# _config.yml

# Site settings
title: "Sarvodaya's Homepage"
description: "Bookmark this to keep an eye on my project updates!"

# Theme settings
theme: jekyll-theme-minimal

# Other settings can be added below as needed
